# Generated by Django 5.1.1 on 2024-10-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('bandera', models.ImageField(null=True, upload_to='banderas/', verbose_name='FotoBandera')),
                ('escudo', models.ImageField(null=True, upload_to='escudos/', verbose_name='FotoEscudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('picture', models.ImageField(null=True, upload_to='jugador/', verbose_name='FotoJugador')),
                ('birthday', models.DateField(verbose_name='Nacimiento')),
                ('position', models.CharField(choices=[('P', 'Portero'), ('D', 'Defensa'), ('C', 'Centrocampista'), ('D', 'Delantero')], default='D', max_length=1, verbose_name='Posicion')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='numero')),
                ('titular', models.BooleanField(default=True, verbose_name='titular')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial2026_aplicacion.equipos', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'db_table': 'jugadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('picture', models.ImageField(null=True, upload_to='director/', verbose_name='FotoDirector')),
                ('birthday', models.DateField(verbose_name='Nacimiento')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol')),
                ('seleccion', models.ManyToManyField(to='mundial2026_aplicacion.equipos', verbose_name='seleccion')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial2026_aplicacion.nacionalidad', verbose_name='nacionalidad')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'db_table': 'entrenadores',
                'ordering': ['id'],
            },
        ),
    ]
