# Generated by Django 5.1.1 on 2024-10-02 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial2026_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('picture', models.ImageField(null=True, upload_to='director/', verbose_name='FotoDirector')),
                ('birthday', models.DateField(verbose_name='Nacimiento')),
                ('rol', models.CharField(max_length=100, verbose_name='Rol')),
                ('seleccion', models.ManyToManyField(to='mundial2026_aplicacion.equipos', verbose_name='seleccion')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mundial2026_aplicacion.nacionalidad', verbose_name='nacionalidad')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'db_table': 'entrenadores',
                'ordering': ['id'],
            },
        ),
    ]
